version: '3.5'

services:
  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    ports:
      - "9000:9000"
      - "9001:9001"

  postgres:
    image: postgres:alpine
    command: postgres -N 500 -B 4096MB
    environment:
      POSTGRES_PASSWORD: REPLACE_ME
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"