// Code generated by ent, DO NOT EDIT.

package ent

import (
	"memekitchen/ent/schema"
	"memekitchen/ent/template"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	templateFields := schema.Template{}.Fields()
	_ = templateFields
	// templateDescName is the schema descriptor for name field.
	templateDescName := templateFields[0].Descriptor()
	// template.NameValidator is a validator for the "name" field. It is called by the builders before save.
	template.NameValidator = templateDescName.Validators[0].(func(string) error)
}
